SESSION_TYPE_TALK = 1
SESSION_TYPE_LIGHTNING_TALK = 2
SESSION_TYPE_BREAK = 3
SESSION_TYPE_CHOICES = (
    (SESSION_TYPE_TALK, 'Talk'),
    (SESSION_TYPE_LIGHTNING_TALK, 'Lightning Talk'),
    (SESSION_TYPE_BREAK, 'Break'),
)

SESSION_STATUS_DRAFT = 1
SESSION_STATUS_PUBLISHED = 2
SESSION_STATUS_CHOICES = (
    (SESSION_STATUS_DRAFT, 'Draft'),
    (SESSION_STATUS_PUBLISHED, 'Published'),
)
